// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'invoice_sell_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

InvoiceSell _$InvoiceSellFromJson(Map<String, dynamic> json) => InvoiceSell(
      VendorId: (json['VendorId'] as num?)?.toInt() ?? 0,
      buildingNo: json['buildingNo'] as num? ?? 1,
      invoiceNo: (json['invoiceNo'] as num?)?.toInt() ?? 0,
      userNumber: json['userNumber'] as String? ?? '0',
      billTypeNo: (json['billTypeNo'] as num?)?.toInt() ?? 33,
      storeNo: (json['storeNo'] as num?)?.toInt() ?? 1,
      aName: json['aName'] as String? ?? "زبون عادي",
      eName: json['eName'] as String? ?? "Normal Customer",
      isCash: json['isCash'] ?? 0,
      dateG: json['dateG'] as String? ?? '2024-03-29 17:41:08.537',
      dateH: json['dateH'] as String? ?? '14450920',
      isDelivered: json['isDelivered'] ?? 0,
      isOutDelivery: json['isOutDelivery'] ?? 0,
      shipCost: json['shipCost'] as num? ?? 0.0,
      billToBuildingNo: json['billToBuildingNo'] as num? ?? 1,
      isInventory1GaveIt: json['isInventory1GaveIt'] ?? 0,
      isInventory2ReceivedIt: json['isInventory2ReceivedIt'] ?? 0,
      isPostedStock: json['isPostedStock'] ?? 0,
      isDeleted: json['isDeleted'] ?? 0,
      isVoid: json['isVoid'] ?? 0,
      isPosted: json['isPosted'] ?? 0,
      isGLPosted: json['isGLPosted'] ?? 0,
      isPayments: json['isPayments'] ?? 0,
      isFastInvoice: json['isFastInvoice'] ?? 0,
      isDeposited: json['isDeposited'] ?? 0,
      isCleared: json['isCleared'] ?? 0,
      amountLeftAfterAllBills: json['amountLeftAfterAllBills'] as num? ?? 0.0,
      collectedAmountFromOtherBills:
          json['collectedAmountFromOtherBills'] as num? ?? 0.0,
      note: json['note'] as String? ?? "",
      isItemOrUnit: json['isItemOrUnit'] ?? 0,
      isUseInOutInvoice: json['isUseInOutInvoice'] ?? 0,
      isAccountingForOthers: json['isAccountingForOthers'] ?? 0,
      personNo: (json['personNo'] as num?)?.toInt() ?? 1,
      telephone: json['telephone'] as String?,
      sumPayed: json['sumPayed'] as num? ?? 0.0,
      subTotal: json['subTotal'] as num? ?? 0.0,
      subTotalDiscount: json['subTotalDiscount'] as num? ?? 0.0,
      subNetTotal: json['subNetTotal'] as num? ?? 0.0,
      subNetTotalPlusTax: json['subNetTotalPlusTax'] as num? ?? 0.0,
      subCount: (json['subCount'] as num?)?.toInt() ?? 0,
      subLeftQuantity: json['subLeftQuantity'] as num? ?? 0.0,
      subQuantity: json['subQuantity'] as num? ?? 0.0,
      amountCalculated: json['amountCalculated'] as num? ?? 0.0,
      discount: json['discount'] as num? ?? 0.0,
      totalDiscount: json['totalDiscount'] as num? ?? 0.0,
      amountPayed01: json['amountPayed01'] as num? ?? 0.0,
      amountPayed02: json['amountPayed02'] as num? ?? 0.0,
      amountPayed03: json['amountPayed03'] as num? ?? 0.0,
      amountPayed04: json['amountPayed04'] as num? ?? 0.0,
      amountPayed05: json['amountPayed05'] as num? ?? 0.0,
      amountLeft: json['amountLeft'] as num? ?? 0.0,
      amountCalculatedPayed: json['amountCalculatedPayed'] as num? ?? 0.0,
      isCompleted: json['isCompleted'] ?? 0,
      taxRate1_Percentage: json['taxRate1_Percentage'] as num? ?? 0.0,
      taxRate2_Percentage: json['taxRate2_Percentage'] as num? ?? 0.0,
      isCalculateTax2OnTax1: json['isCalculateTax2OnTax1'] ?? 0,
      isTax1OnShipping: json['isTax1OnShipping'] ?? 0,
      isTax2OnShipping: json['isTax2OnShipping'] ?? 0,
      taxRate1_Total: json['taxRate1_Total'] as num? ?? 0.0,
      taxRate2_Total: json['taxRate2_Total'] as num? ?? 0.0,
      isOneInvoiceUploaded: json['isOneInvoiceUploaded'] ?? 0,
      cashRegisterNo_BuildingNo: json['cashRegisterNo_BuildingNo'] as num? ?? 1,
      invoiceVATID: json['invoiceVATID'] as String?,
      clientVendorNo: json['clientVendorNo'] as num?,
      isUploadedToMainBranch: json['isUploadedToMainBranch'] ?? 0,
      isPostedToTransactions: json['isPostedToTransactions'] ?? 0,
      dateG_PerDay: json['dateG_PerDay'] as String?,
      dateG_PerMonth: (json['dateG_PerMonth'] as num?)?.toInt() ?? 0,
      dateG_PerYearQuarter:
          (json['dateG_PerYearQuarter'] as num?)?.toInt() ?? 0,
      dateG_PerYearHalf: (json['dateG_PerYearHalf'] as num?)?.toInt() ?? 0,
      dateG_PerYear: (json['dateG_PerYear'] as num?)?.toInt() ?? 0,
      VATTypeNo: (json['VATTypeNo'] as num?)?.toInt() ?? 1,
      VATGroupNo: (json['VATGroupNo'] as num?)?.toInt() ?? 1,
      profitMarginTotal: json['profitMarginTotal'] as num? ?? 0.0,
      customerCashGiven: json['customerCashGiven'] as num? ?? 0.0,
      customerCashReturned: json['customerCashReturned'] as num? ?? 0.0,
      price_differenceFromFirstPriceTotal:
          json['price_differenceFromFirstPriceTotal'] as num? ?? 0.0,
      print_numOfCopies: (json['print_numOfCopies'] as num?)?.toInt() ?? 0,
      isPrintPartial: json['isPrintPartial'] ?? 0,
      cardAmount_Visa: json['cardAmount_Visa'] as num? ?? 0.0,
      cardAmount_SPAN: json['cardAmount_SPAN'] as num? ?? 0.0,
      runningCostAvg_diffrenceWhithPriceTotal:
          json['runningCostAvg_diffrenceWhithPriceTotal'] as num? ?? 0.0,
      profitMarginTotal_fromAvgCost:
          json['profitMarginTotal_fromAvgCost'] as num? ?? 0.0,
      runningCostAvgTotal: json['runningCostAvgTotal'] as num? ?? 0.0,
      buyPrice_costPriceTotal: json['buyPrice_costPriceTotal'] as num? ?? 0.0,
      primaryUnit_QuantityTotal:
          json['primaryUnit_QuantityTotal'] as num? ?? 0.0,
      paperBillNum: json['paperBillNum'] as String?,
      isReturnedFullyByReturnInvoice:
          json['isReturnedFullyByReturnInvoice'] ?? 0,
      weightTotal: json['weightTotal'] as num? ?? 0.0,
      subNetTotal_ExecludingTax:
          json['subNetTotal_ExecludingTax'] as num? ?? 0.0,
      device_mileage: json['device_mileage'] as num? ?? 0.0,
      device_next_mileage: json['device_next_mileage'] as num? ?? 0.0,
      Inv_billTypeNo: (json['Inv_billTypeNo'] as num?)?.toInt() ?? 0,
      calculatedPayed: json['calculatedPayed'] as num? ?? 0.0,
      amountPayed: json['amountPayed'] as num? ?? 0.0,
      calculatedCreditAmount: json['calculatedCreditAmount'] as num? ?? 0.0,
      calculatedDebitAmount: json['calculatedDebitAmount'] as num? ?? 0.0,
      isCreateGlass: json['isCreateGlass'] ?? 0,
      rentQuantity: json['rentQuantity'] as num? ?? 0.0,
      isHangerOrFold: json['isHangerOrFold'] ?? 0,
      isSpot: json['isSpot'] ?? 0,
      isFastCleaning: json['isFastCleaning'] ?? 0,
      isLost: json['isLost'] ?? 0,
      isPaperInvoiceReturned: json['isPaperInvoiceReturned'] ?? 0,
      trainingHourseToBeGiven: json['trainingHourseToBeGiven'] as num? ?? 0.0,
      trainingHourseLeft: json['trainingHourseLeft'] as num? ?? 0.0,
      gaztInvoiceNumber: json['gaztInvoiceNumber'] as String? ?? '0',
      gaztUniqueInvoiceIdentifier:
          json['gaztUniqueInvoiceIdentifier'] as String? ??
              "2b429c0a-04c6-4fec-8372-6785d2602279",
      gaztInvoiceTypeCode:
          (json['gaztInvoiceTypeCode'] as num?)?.toInt() ?? 388,
      linesCount: (json['linesCount'] as num?)?.toInt() ?? 0,
      isAgentGivenHisMoney: json['isAgentGivenHisMoney'] ?? 0,
    );

Map<String, dynamic> _$InvoiceSellToJson(InvoiceSell instance) =>
    <String, dynamic>{
      'VendorId': instance.VendorId,
      'buildingNo': instance.buildingNo,
      'invoiceNo': instance.invoiceNo,
      'userNumber': instance.userNumber,
      'billTypeNo': instance.billTypeNo,
      'storeNo': instance.storeNo,
      'aName': instance.aName,
      'eName': instance.eName,
      'isCash': instance.isCash,
      'dateG': instance.dateG,
      'dateH': instance.dateH,
      'isDelivered': instance.isDelivered,
      'isOutDelivery': instance.isOutDelivery,
      'shipCost': instance.shipCost,
      'billToBuildingNo': instance.billToBuildingNo,
      'isInventory1GaveIt': instance.isInventory1GaveIt,
      'isInventory2ReceivedIt': instance.isInventory2ReceivedIt,
      'isPostedStock': instance.isPostedStock,
      'isDeleted': instance.isDeleted,
      'isVoid': instance.isVoid,
      'isPosted': instance.isPosted,
      'isGLPosted': instance.isGLPosted,
      'isPayments': instance.isPayments,
      'isFastInvoice': instance.isFastInvoice,
      'isDeposited': instance.isDeposited,
      'isCleared': instance.isCleared,
      'amountLeftAfterAllBills': instance.amountLeftAfterAllBills,
      'collectedAmountFromOtherBills': instance.collectedAmountFromOtherBills,
      'note': instance.note,
      'isItemOrUnit': instance.isItemOrUnit,
      'isUseInOutInvoice': instance.isUseInOutInvoice,
      'isAccountingForOthers': instance.isAccountingForOthers,
      'personNo': instance.personNo,
      'telephone': instance.telephone,
      'sumPayed': instance.sumPayed,
      'subTotal': instance.subTotal,
      'subTotalDiscount': instance.subTotalDiscount,
      'subNetTotal': instance.subNetTotal,
      'subNetTotalPlusTax': instance.subNetTotalPlusTax,
      'subCount': instance.subCount,
      'subLeftQuantity': instance.subLeftQuantity,
      'subQuantity': instance.subQuantity,
      'amountCalculated': instance.amountCalculated,
      'discount': instance.discount,
      'totalDiscount': instance.totalDiscount,
      'amountPayed01': instance.amountPayed01,
      'amountPayed02': instance.amountPayed02,
      'amountPayed03': instance.amountPayed03,
      'amountPayed04': instance.amountPayed04,
      'amountPayed05': instance.amountPayed05,
      'amountLeft': instance.amountLeft,
      'amountCalculatedPayed': instance.amountCalculatedPayed,
      'isCompleted': instance.isCompleted,
      'taxRate1_Percentage': instance.taxRate1_Percentage,
      'taxRate2_Percentage': instance.taxRate2_Percentage,
      'isCalculateTax2OnTax1': instance.isCalculateTax2OnTax1,
      'isTax1OnShipping': instance.isTax1OnShipping,
      'isTax2OnShipping': instance.isTax2OnShipping,
      'taxRate1_Total': instance.taxRate1_Total,
      'taxRate2_Total': instance.taxRate2_Total,
      'isOneInvoiceUploaded': instance.isOneInvoiceUploaded,
      'cashRegisterNo_BuildingNo': instance.cashRegisterNo_BuildingNo,
      'invoiceVATID': instance.invoiceVATID,
      'clientVendorNo': instance.clientVendorNo,
      'isUploadedToMainBranch': instance.isUploadedToMainBranch,
      'isPostedToTransactions': instance.isPostedToTransactions,
      'dateG_PerDay': instance.dateG_PerDay,
      'dateG_PerMonth': instance.dateG_PerMonth,
      'dateG_PerYearQuarter': instance.dateG_PerYearQuarter,
      'dateG_PerYearHalf': instance.dateG_PerYearHalf,
      'dateG_PerYear': instance.dateG_PerYear,
      'VATTypeNo': instance.VATTypeNo,
      'VATGroupNo': instance.VATGroupNo,
      'profitMarginTotal': instance.profitMarginTotal,
      'customerCashGiven': instance.customerCashGiven,
      'customerCashReturned': instance.customerCashReturned,
      'price_differenceFromFirstPriceTotal':
          instance.price_differenceFromFirstPriceTotal,
      'print_numOfCopies': instance.print_numOfCopies,
      'isPrintPartial': instance.isPrintPartial,
      'cardAmount_Visa': instance.cardAmount_Visa,
      'cardAmount_SPAN': instance.cardAmount_SPAN,
      'runningCostAvg_diffrenceWhithPriceTotal':
          instance.runningCostAvg_diffrenceWhithPriceTotal,
      'profitMarginTotal_fromAvgCost': instance.profitMarginTotal_fromAvgCost,
      'runningCostAvgTotal': instance.runningCostAvgTotal,
      'buyPrice_costPriceTotal': instance.buyPrice_costPriceTotal,
      'primaryUnit_QuantityTotal': instance.primaryUnit_QuantityTotal,
      'paperBillNum': instance.paperBillNum,
      'isReturnedFullyByReturnInvoice': instance.isReturnedFullyByReturnInvoice,
      'weightTotal': instance.weightTotal,
      'subNetTotal_ExecludingTax': instance.subNetTotal_ExecludingTax,
      'device_mileage': instance.device_mileage,
      'device_next_mileage': instance.device_next_mileage,
      'Inv_billTypeNo': instance.Inv_billTypeNo,
      'calculatedPayed': instance.calculatedPayed,
      'amountPayed': instance.amountPayed,
      'calculatedCreditAmount': instance.calculatedCreditAmount,
      'calculatedDebitAmount': instance.calculatedDebitAmount,
      'isCreateGlass': instance.isCreateGlass,
      'rentQuantity': instance.rentQuantity,
      'isHangerOrFold': instance.isHangerOrFold,
      'isSpot': instance.isSpot,
      'isFastCleaning': instance.isFastCleaning,
      'isLost': instance.isLost,
      'isPaperInvoiceReturned': instance.isPaperInvoiceReturned,
      'trainingHourseToBeGiven': instance.trainingHourseToBeGiven,
      'trainingHourseLeft': instance.trainingHourseLeft,
      'gaztInvoiceNumber': instance.gaztInvoiceNumber,
      'gaztUniqueInvoiceIdentifier': instance.gaztUniqueInvoiceIdentifier,
      'gaztInvoiceTypeCode': instance.gaztInvoiceTypeCode,
      'linesCount': instance.linesCount,
      'isAgentGivenHisMoney': instance.isAgentGivenHisMoney,
    };
